services:

  db:
    container_name: backend_db
    image: postgres
    environment:
      POSTGRES_USER: db 
      POSTGRES_PASSWORD: db 
      POSTGRES_DB: backend_db
    ports:
      - "5432:5432"
  
  pgadmin:
    container_name: backend_pgadmin
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com 
      PGADMIN_DEFAULT_PASSWORD: admin 
    ports:
      - "15000:80"